#!/usr/bin/env zsh

if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS=""
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

# for each dotfiles folder, "stow" it
for stow_folder in $(echo $STOW_FOLDERS | sed "s/,/ /g"); do
    stow -D $stow_folder
    stow $stow_folder
done
