# config.toml configuration for codex
#
# in practice, this configuration is geared towards read-only exploration by
# default; any CLI tool is allowed as long as it doesn't edit anything; codex's
# sandbox uses seccomp configurations, which disallow edits with Permission
# denied (unless in proper workspace-write mode or the model asks for
# permission); any filesystem file can be read; the model has some local tools
# available to inspect the filesystem (too many to list them all, but a few
# categories are):
# - functions.*
#   - execute a CLI command, apply a patch to a file (edit tool),
# view an image; the model usually reads files by cat, and edits by apply_patch
#   - planning and interaction by update_plan and request_user_input
#   - spawn agent, send input, resume agent, wait, close agent
# - multi_tool_use.parallel: runs multiple tools in parallel
# - web.* tools: search, open, click, find, screenshot, weather, time
#
# codex can ask to edit files or run destructive commands even in read-only
# mode, but it needs explicit user approval for this (via sandbox_mode:
# require_escalated), and it also needs to be in the specific workspace; even if
# codex is in read-only mode and asks for escalated permissions, unless it is in
# the correct directory (the directory with the file to be edited or a parent of
# it, i.e. the workspace) it gets denied; it may still ask to modify random
# files outside the workspace through CLI commands, though; this is not required
# for per-project stuff in workspace-write mode; if it doesn't pass escalation
# permissions, it gets auto-denied by the sandbox
#
# network access is denied by default, so commands like curl, wget etc. need to
# also pass through user permission; web fetch is a separate server side tool
# which is allowed in read-only mode by default

# options: untrusted, on-request, never
# ask for tool use approval
# with untrusted, the model always asks before using the tools
# with never, it never asks
# with on-request, it decides whether the tool it runs require user permission
approval_policy = "on-request"

# options: disabled, cached, live 
# this refers to run a web searching tool
# cached means an OpenAI maintained index; data might be stale, but avoids
# prompt injections
web_search = "cached"

# options: none, friendly, pragmatic
personality = "pragmatic"

# options: read-only, workspace-write, danger-full-access
# sandboxing means environment protection (implemented with seccomp rules)
# with read-only, it means the model has read-only access to the filesystem
# with workspace-write, it has read/write access to the local .git workspace +
# /tmp, or read-only otherwise
sandbox_mode = "read-only"

model = "gpt-5.4"
model_reasoning_effort = "xhigh"

[sandbox_workspace_write]
# this option is different from web_search; web_search itself is a server-side
# tool that allows the model to look up information; on the other hand,
# network_access allows local commands such as curl; the model is free to use
# web_search, but network access is disabled; the model may still ask to use
# e.g. curl, but requires user approval
# see also: https://github.com/openai/codex/issues/3139#issuecomment-3254058065
# see also: https://developers.openai.com/codex/security
network_access = false

[features]
multi_agent = true

[agents]
max_threads = 6
max_depth = 2

[projects."/home/alex/projects/dotfiles/vim/.config/nvim"]
trust_level = "trusted"
