# canonical nanoemoji config template used by add_svg_icon.py
family = "Custom Icon Fonts"
output_file = "CustomIconFonts.ttf"
color_format = "glyf_colr_1"
upem = 1024
ascender = 950
descender = -250

[axis.wght]
name = "Weight"
default = 400

[master.regular]
style_name = "Regular"
srcs = ["emoji_u*.svg"]

[master.regular.position]
wght = 400
